# default_stages: [commit, push]
# Список файлов, которые необходимо игнорировать при проверке pre-commit hooks
exclude: '^(models/|data/|notebooks/|config/|mlflow/|.dvc/)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=10000']
  - repo: local
    hooks:
      # RUFF
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [ python ]
      # MYPY
      # - id: mypy
      #   name: mypy
      #   entry: poetry run mypy
      #   require_serial: true
      #   language: system
      #   # args: [--strict]

      # PYLINT
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=pyproject.toml"
          ]
