version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    # volumes:
    #   - ./backend:/app/backend
    ports:
      - ${BACKEND_PORT}:8000
    env_file:
      - ./.env
    networks:
      - ml_network

networks:
  ml_network:
