version: '3.8'

services:
  app:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - ml_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - ${BACKEND_PORT}:8000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RESID_PASSWORD=${RESID_PASSWORD}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION_DESCRIPTION=${QDRANT_COLLECTION_DESCRIPTION}
      - QDRANT_COLLECTION_TITLES=${QDRANT_COLLECTION_TITLES}
      - QDRANT_EMBEDDER=${QDRANT_EMBEDDER}
      - POSTGRE_HOST=${POSTGRE_HOST}
      - POSTGRE_PORT=${POSTGRE_PORT}
      - POSTGRE_USER=${POSTGRE_USER}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRE_DATABASE=${POSTGRE_DATABASE}
      - POSTGRE_BOOK_TABLE=${POSTGRE_BOOK_TABLE}
      - POSTGRE_USER_TABLE=${POSTGRE_USER_TABLE}
    networks:
      - ml_network

networks:
  ml_network:
