version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile

  auth_service:
    build:
      context: backend/auth_service
      dockerfile: Dockerfile
    # volumes:
    #   - ./backend:/app/backend
    ports:
      - ${BACKEND_AUTH_PORT}:8001
    env_file:
      - ./.env
    networks:
      - ml_network

  recsys_service:
    build:
      context: backend/recsys_service
      dockerfile: Dockerfile
    # volumes:
    #   - ./backend:/app/backend
    ports:
      - ${BACKEND_RECSYS_PORT}:8003
    env_file:
      - ./.env
    environment:
      - BACKEND_SEARCH_HOST=search_service
    networks:
      - ml_network

  search_service:
    build:
      context: backend/search_service
      dockerfile: Dockerfile
    # volumes:
    #   - ./backend:/app/backend
    ports:
      - ${BACKEND_SEARCH_PORT}:8002
    env_file:
      - ./.env
    networks:
      - ml_network

networks:
  ml_network:
