version: '3.8'

services:
  app:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - ml_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - ${BACKEND_PORT}:8000
    env_file:
      - ./.env
    networks:
      - ml_network

networks:
  ml_network:
