"""create books table

Revision ID: 06fa188bea8a
Revises: 23b6c4f8d774
Create Date: 2024-09-05 03:42:16.301865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fa188bea8a'
down_revision: Union[str, None] = '23b6c4f8d774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_user', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('books_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_table',
    sa.Column('Title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Author', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ID', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
