"""Initial revision

Revision ID: 23b6c4f8d774
Revises: 
Create Date: 2024-09-05 03:03:32.888520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b6c4f8d774'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_table',
    sa.Column('Title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Author', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ID', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
