"""update users table

Revision ID: 406cc191777d
Revises: e661b4e4f805
Create Date: 2024-09-05 03:52:01.942851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406cc191777d'
down_revision: Union[str, None] = 'e661b4e4f805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_table', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('books_table', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('books_table', 'ID',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('books_table', 'Title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('books_table', 'Author',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('books_table', 'Link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('books_table', 'Image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('books_table', 'Category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('books_table', 'Description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('books_table', 'Info',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_books_table_ID'), 'books_table', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_table_ID'), table_name='books_table')
    op.alter_column('books_table', 'Info',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('books_table', 'Description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('books_table', 'Category',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('books_table', 'Image',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('books_table', 'Link',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('books_table', 'Author',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('books_table', 'Title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('books_table', 'ID',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('books_table', 'updated_at')
    op.drop_column('books_table', 'created_at')
    # ### end Alembic commands ###
