"""try to fix books table

Revision ID: 9b90608f69f6
Revises: 406cc191777d
Create Date: 2024-09-05 15:12:29.663607

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b90608f69f6"
down_revision: Union[str, None] = "406cc191777d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books_table", "Title", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("books_table", "Author", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("books_table", "Link", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("books_table", "Image", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("books_table", "Category", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("books_table", "Description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("books_table", "Info", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "users",
        "uid",
        existing_type=sa.String(),  # укажите текущий тип данных столбца (например, String)
        type_=sa.UUID(),
        postgresql_using="uid::uuid",  # преобразование данных при изменении типа
    )
    op.alter_column("users", "login", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "is_user", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("true")
    )
    op.alter_column(
        "users", "is_admin", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("false")
    )
    op.alter_column(
        "users", "is_super_admin", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "is_super_admin", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("false")
    )
    op.alter_column(
        "users", "is_admin", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("false")
    )
    op.alter_column(
        "users", "is_user", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("true")
    )
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "login", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "uid", existing_type=sa.UUID(), type_=sa.VARCHAR(), existing_nullable=False)
    op.alter_column("books_table", "Info", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("books_table", "Description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("books_table", "Category", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("books_table", "Image", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("books_table", "Link", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("books_table", "Author", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("books_table", "Title", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
