"""create books table

Revision ID: e661b4e4f805
Revises: 06fa188bea8a
Create Date: 2024-09-05 03:48:43.489963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e661b4e4f805'
down_revision: Union[str, None] = '06fa188bea8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_table',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Author', sa.String(length=255), nullable=False),
    sa.Column('Link', sa.String(length=255), nullable=False),
    sa.Column('Image', sa.String(length=255), nullable=False),
    sa.Column('Category', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.Column('Info', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_books_table_ID'), 'books_table', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_table_ID'), table_name='books_table')
    op.drop_table('books_table')
    # ### end Alembic commands ###
