apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-front-app
  template:
    metadata:
      labels:
        app: books-front-app
    spec:
      containers:
      - name: books-front-app
        image: borinskihsd/books-front-app:latest
        ports:
        - containerPort: 5173
        env:
        # ConfigMap variables

        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: books-front-config
              key: NODE_ENV
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
