apiVersion: v1
kind: Service
metadata:
  name: books-front-service
spec:
  type: LoadBalancer
  selector:
    app: books-front-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
